services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    command: python3 /backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    tty: true

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    environment:
      - POSTGRES_DB=qiita_django
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/app:/app
      - front_node_modules:/app/node_modules
    command:
      - "sh"
      - "-c"
      - "npm install && npm start --port 80"
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  front_node_modules:
